version: '3.11'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///database.db
